### ISSUE TITLE
Wrong path to the config file

### ISSUE THREAD

**Issue by visualfanatic** [machine-data/docker-oauth2_proxy#3]
In [this section](https://github.com/machine-data/docker-oauth2_proxy/blob/a5a941b86f70485d86dcf887f4173dfd95e45f24/README.md#configuration-file), the path to the config file is: `/config/oauth2_proxy.cfg`, where the `docker-entrypoint.sh` is looking for the config in the `/conf` directory.
https://github.com/machine-data/docker-oauth2_proxy/blob/a5a941b86f70485d86dcf887f4173dfd95e45f24/docker-entrypoint.sh#L16
https://github.com/machine-data/docker-oauth2_proxy/blob/a5a941b86f70485d86dcf887f4173dfd95e45f24/docker-entrypoint.sh#L83
https://github.com/machine-data/docker-oauth2_proxy/blob/a5a941b86f70485d86dcf887f4173dfd95e45f24/docker-entrypoint.sh#L87
https://github.com/machine-data/docker-oauth2_proxy/blob/a5a941b86f70485d86dcf887f4173dfd95e45f24/docker-entrypoint.sh#L90
https://github.com/machine-data/docker-oauth2_proxy/blob/a5a941b86f70485d86dcf887f4173dfd95e45f24/docker-entrypoint.sh#L94
https://github.com/machine-data/docker-oauth2_proxy/blob/a5a941b86f70485d86dcf887f4173dfd95e45f24/docker-entrypoint.sh#L98

Would you be willing to merge the changes if I make PR for this issue?

**Comment by jodok** [comment]
sure
