### ISSUE TITLE
OAUTH2_PROXY_PROXY_PREFIX doesn't work.

### ISSUE THREAD

**Issue by RichardN** [machine-data/docker-oauth2_proxy#4]
In the oauth2_proxy parameter file, this is the odd one out as it is called proxy-prefix.   As far as I can tell it is the only parameter which uses dash instead of underscore.   I forked the repo (mainly to use a fork of oauth2_proxy which requires and additional parameter), but you can see how I bodged it at 

https://github.com/RichardN/docker-oauth2_proxy/blob/master/docker-entrypoint.sh

**Comment by jodok** [comment]
thanks! fixed with https://github.com/machine-data/docker-oauth2_proxy/commit/1d9dc9b7ea6d1f49625f8df772d5ae4fed6dbd69
